global:
  resolve_timeout: 5m

route:
  receiver: default-log
  group_by: ["alertname", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity="warning"
      receiver: default-log

receivers:
  - name: default-log
    webhook_configs:
      - url: http://127.0.0.1:5001/alertmanager/webhook
        send_resolved: true
